config/routes.rb
Rails.application.routes.draw do
  resources :links
  root 'splash#splash'

  resources :sessions, only: [:new, :create, :destroy]
  match '/login',  to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: ['get','delete']

  get '/profile', to: 'users#show'

  get ':wildcard' => 'links#reroute'

end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :requests
  belongs_to :user

  validates :full_url, :short_url, presence: true
  validates :full_url, exclusion: { in: ["http://"], message: "can't be blank" }
  validates :short_url, uniqueness: true

  def click_count
    requests.count
  end

  def has_clicks?
    click_count > 0
  end

  def user_agent_frequency
    requests.group("requests.user_agent").count
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :link

  validates :link, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, uniqueness: true, presence: true
  validates :password, length: {minimum: 8}

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user != nil
  end

  def require_login
    redirect_to login_path, notice: 'Please log in.' unless logged_in?
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: :reroute
  before_action :current_user_must_own_link, only: [:show, :edit, :update, :destroy]

  def reroute
    link = Link.find_by(short_url: params[:wildcard])
    if link
      Request.create(
        user_agent: request.headers["User-Agent"],
        accept_language: request.headers["Accept-Language"],
        path: request.path,
        link: link
        )
      redirect_to link.full_url
    else
      render plain: "404 Not Found", status: 404
    end
  end

  def index
    @links = current_user.links
  end

  def show
  end

  def new
    @link = Link.new
  end

  def edit
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to @link, notice: 'Link was successfully created.'
    else
      render :new
    end
  end

  def update
    if @link.update(link_params)
      redirect_to @link, notice: 'Link was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @link.destroy
    redirect_to links_url, notice: 'Link was successfully destroyed.'
  end

  private
    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:full_url, :short_url).merge(user: current_user)
    end

    def current_user_must_own_link
      render plain: "403 Unauthorized", status: 403 unless @link.user == current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to root_path, notice: "You're already logged in." if logged_in?
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to :root, notice: 'Successfully logged in.'
    else
      flash.now[:error] = "Wrong username or password."
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to :root, notice: 'Successfully logged out.'
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def splash
    if logged_in?
      redirect_to '/links'
    else
      redirect_to 'http://www.samuelrblackman.com'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def show
    @user = current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_url %><br>
    <%= f.text_field :full_url, value: @link.full_url || "http://" %>
  </div>
  <div class="field">
    <%= f.label :short_url %><br>
    <%= request.scheme %>://<%= request.host %>/<%= f.text_field :short_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Links</h1>

<table>
  <thead>
    <tr>
      <th>Full url</th>
      <th>Short url</th>
      <th>Click count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.full_url %></td>
        <td><%= link.short_url %></td>
        <td><%= link.click_count %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full url:</strong>
  <%= @link.full_url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= @link.short_url %>
</p>

<p>
  <strong>Click count:</strong>
  <%= @link.click_count %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

<h2>User Agents</h2>
<% if @link.has_clicks? %>
  <table>
  	<tr>
  		<th>User agent string</th>
      <th>Count</th>
  	</tr>
    <% @link.user_agent_frequency.each do |user_agent, count| %>
      <tr>
        <td><%= user_agent %></td>
        <td><%= count %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>User information will appear as soon as people have used the shortened link.</p>
<% end %>

app/views/splash/splash.html.erb
<p id="notice"><%= notice %></p>
<h3>Welcome</h3>
<p>This is a private link shortening application.</p>
<div>
  <%= link_to "Click here", login_path %> to log in.
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>